final teamsData = [
  {
    "id": 14,
    "fullName": "India",
    "shortName": "India",
    "abbreviation": "IND",
    "primaryColour": "#0057AF",
    "secondaryColour": "#FF5500",
  },
  {
    "id": 11,
    "fullName": "England",
    "shortName": "England",
    "abbreviation": "ENG",
    "primaryColour": "#04064D",
    "secondaryColour": "#FE1448",
  },
  {
    "id": 17,
    "fullName": "Afghanistan",
    "shortName": "Afghanistan",
    "abbreviation": "AFG",
    "primaryColour": "#0954AF",
    "secondaryColour": "#FC0011",
  },
  {
    "id": 15,
    "fullName": "Australia",
    "shortName": "Australia",
    "abbreviation": "AUS",
    "primaryColour": "#0B661E",
    "secondaryColour": "#FFD500",
  },
  {
    "id": 22,
    "fullName": "Bangladesh",
    "shortName": "Bangladesh",
    "abbreviation": "BAN",
    "primaryColour": "#00644C",
    "secondaryColour": "#F91A22",
  },
  {
    "id": 16,
    "fullName": "New Zealand",
    "shortName": "New Zealand",
    "abbreviation": "NZ",
    "primaryColour": "#1F1F1F",
    "secondaryColour": "#E8EBED",
  },
  {
    "id": 20,
    "fullName": "Pakistan",
    "shortName": "Pakistan",
    "abbreviation": "PAK",
    "primaryColour": "#206500",
    "secondaryColour": "#70E101",
  },
  {
    "id": 19,
    "fullName": "South Africa",
    "shortName": "South Africa",
    "abbreviation": "SA",
    "primaryColour": "#0B5425",
    "secondaryColour": "#F5AB00",
  },
  {
    "id": 68,
    "fullName": "Netherlands",
    "shortName": "Netherlands",
    "abbreviation": "NED",
    "primaryColour": "#EF6C00",
    "secondaryColour": "#212649",
  },
  {
    "id": 13,
    "fullName": "Sri Lanka",
    "shortName": "Sri Lanka",
    "abbreviation": "SL",
    "primaryColour": "#1B2E96",
    "secondaryColour": "#FFC500",
  },
];
