Map<String, String> languageNamesMap = {
  "af-ZA": "Afrikaans (South Africa)",
  "am-ET": "Amharic (Ethiopia)",
  "ar-DZ": "Arabic (Algeria)",
  "ar-EG": "Arabic (Egypt)",
  "ar-JO": "Arabic (Jordan)",
  "ar-KW": "Arabic (Kuwait)",
  "ar-LB": "Arabic (Lebanon)",
  "ar-MY": "Arabic (Malaysia)",
  "ar-SA": "Arabic (Saudi Arabia)",
  "ar-TN": "Arabic (Tunisia)",
  "ar-AE": "Arabic (United Arab Emirates)",
  "az-AZ": "Azerbaijani (Azerbaijan)",
  "be-BY": "Belarusian (Belarus)",
  "bg-BG": "Bulgarian (Bulgaria)",
  "bn-BD": "Bengali (Bangladesh)",
  "bs-BA": "Bosnian (Bosnia and Herzegovina)",
  "ca-ES": "Catalan (Spain)",
  "cs-CZ": "Czech (Czech Republic)",
  "da-DK": "Danish (Denmark)",
  "de-AT": "German (Austria)",
  "de-CH": "German (Switzerland)",
  "de-DE": "German (Germany)",
  "el-GR": "Greek (Greece)",
  "en-AU": "English (Australia)",
  "en-CA": "English (Canada)",
  "en-GB": "English (United Kingdom)",
  "en-IN": "English (India)",
  "en-IE": "English (Ireland)",
  "en-NZ": "English (New Zealand)",
  "en-PH": "English (Philippines)",
  "en-SG": "English (Singapore)",
  "en-US": "English (United States)",
  "en-ZA": "English (South Africa)",
  "es-AR": "Spanish (Argentina)",
  "es-BO": "Spanish (Bolivia)",
  "es-CL": "Spanish (Chile)",
  "es-CO": "Spanish (Colombia)",
  "es-CR": "Spanish (Costa Rica)",
  "es-DO": "Spanish (Dominican Republic)",
  "es-EC": "Spanish (Ecuador)",
  "es-ES": "Spanish (Spain)",
  "es-GT": "Spanish (Guatemala)",
  "es-HN": "Spanish (Honduras)",
  "es-MX": "Spanish (Mexico)",
  "es-NI": "Spanish (Nicaragua)",
  "es-PA": "Spanish (Panama)",
  "es-PE": "Spanish (Peru)",
  "es-PR": "Spanish (Puerto Rico)",
  "es-PY": "Spanish (Paraguay)",
  "es-SV": "Spanish (El Salvador)",
  "es-US": "Spanish (United States)",
  "es-UY": "Spanish (Uruguay)",
  "es-VE": "Spanish (Venezuela)",
  "et-EE": "Estonian (Estonia)",
  "eu-ES": "Basque (Spain)",
  "fa-IR": "Persian (Iran)",
  "fi-FI": "Finnish (Finland)",
  "fil-PH": "Filipino (Philippines)",
  "fr-BE": "French (Belgium)",
  "fr-CA": "French (Canada)",
  "fr-CH": "French (Switzerland)",
  "fr-FR": "French (France)",
  "gl-ES": "Galician (Spain)",
  "gu-IN": "Gujarati (India)",
  "he-IL": "Hebrew (Israel)",
  "hi-IN": "Hindi (India)",
  "hr-HR": "Croatian (Croatia)",
  "hu-HU": "Hungarian (Hungary)",
  "hy-AM": "Armenian (Armenia)",
  "id-ID": "Indonesian (Indonesia)",
  "is-IS": "Icelandic (Iceland)",
  "it-IT": "Italian (Italy)",
  "ja-JP": "Japanese (Japan)",
  "jv-ID": "Javanese (Indonesia)",
  "ka-GE": "Georgian (Georgia)",
  "kk-KZ": "Kazakh (Kazakhstan)",
  "km-KH": "Khmer (Cambodia)",
  "kn-IN": "Kannada (India)",
  "ko-KR": "Korean (South Korea)",
  "ky-KG": "Kyrgyz (Kyrgyzstan)",
  "lo-LA": "Lao (Laos)",
  "lt-LT": "Lithuanian (Lithuania)",
  "lv-LV": "Latvian (Latvia)",
  "mk-MK": "Macedonian (North Macedonia)",
  "ml-IN": "Malayalam (India)",
  "mn-MN": "Mongolian (Mongolia)",
  "mr-IN": "Marathi (India)",
  "ms-MY": "Malay (Malaysia)",
  "my-MM": "Burmese (Myanmar)",
  "nb-NO": "Norwegian Bokmål (Norway)",
  "ne-NP": "Nepali (Nepal)",
  "nl-BE": "Dutch (Belgium)",
  "nl-NL": "Dutch (Netherlands)",
  "nn-NO": "Norwegian Nynorsk (Norway)",
  "or-IN": "Oriya (India)",
  "pa-IN": "Punjabi (India)",
  "pl-PL": "Polish (Poland)",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "ro-RO": "Romanian (Romania)",
  "ru-RU": "Russian (Russia)",
  "si-LK": "Sinhala (Sri Lanka)",
  "sk-SK": "Slovak (Slovakia)",
  "sl-SI": "Slovenian (Slovenia)",
  "sq-AL": "Albanian (Albania)",
  "sr-RS": "Serbian (Serbia)",
  "sv-SE": "Swedish (Sweden)",
  "sw-KE": "Swahili (Kenya)",
  "ta-IN": "Tamil (India)",
  "te-IN": "Telugu (India)",
  "th-TH": "Thai (Thailand)",
  "tr-TR": "Turkish (Turkey)",
  "uk-UA": "Ukrainian (Ukraine)",
  "ur-IN": "Urdu (India)",
  "ur-PK": "Urdu (Pakistan)",
  "uz-UZ": "Uzbek (Uzbekistan)",
  "vi-VN": "Vietnamese (Vietnam)",
  "zh-CN": "Chinese (Simplified, China)",
  "zh-HK": "Chinese (Traditional, Hong Kong)",
  "zh-TW": "Chinese (Traditional, Taiwan)"
};